dependencies:
  flutter:
    sdk: flutter
  firebase_core: latest_version
  firebase_auth: latest_version
  http: latest_version
  provider: latest_version
  flutter_local_notifications: latest_version
  web_socket_channel: latest_version
